export const palette = {
  white: '#FFFFFF',
  black: '#000000',
  transparent: 'transparent',
  ink: {
    lightest: '#8699A4',
    lighter: '#6D7E88',
    light: '#576873',
    medium: '#4B5964',
    base: '#414B54',
    dark: '#31383E',
    darker: '#1F2529',
    darkest: '#0E1316',
  },
  light: {
    pale: '#FFFFFF',
    lightest: '#F5F8FA',
    lighter: '#EDF1F5',
    light: '#E5EBF1',
    base: '#DDE5ED',
    dark: '#C8D5E2',
    darker: '#B7C7D7',
    darkest: '#A6B8CB',
  },
  primary: {
    lightest: '#EAF2FC',
    lighter: '#94C2FF',
    light: '#4791EF',
    base: '#307FE2',
    darkest: '#1A56A0',
  },
  secondary: {
    lightest: '#FFF5EB',
    lighter: '#FDC790',
    light: '#FB9F3F',
    base: '#FF8200',
    darkest: '#D87004',
  },
  success: {
    lightest: '#D8F3DC',
    lighter: '#82E1B5',
    light: '#6FC89E',
    base: '#52B788',
    darkest: '#40916C',
  },
  error: {
    lightest: '#FFE3E0',
    lighter: '#FFACAB',
    light: '#F16360',
    base: '#EE3733',
    darkest: '#B72E2B',
  },
  warning: {
    lightest: '#FFE8DB',
    lighter: '#F6B994',
    light: '#F9965C',
    base: '#F3752B',
    darkest: '#E45C3A',
  },
  info: {
    lightest: '#E3FAFF',
    lighter: '#A8DFEB',
    light: '#5BCAE0',
    base: '#00B4D8',
    darkest: '#0096C7',
  },
  spotify: {
    primary: '#1DB954',
  },
};

export const colors = {
  white: palette.white,
  black: palette.black,
  transparent: palette.transparent,
  background: palette.light.lighter,
  separator: palette.light.light,
  borderUnfocused: palette.light.darker,
  border: palette.light.darkest,
  imageBorder: palette.light.dark,
  text: palette.ink.light,
  textDisabled: palette.light.darkest,
  textAccented: palette.ink.darkest,
  textMedium: palette.ink.medium,
  textFaded: palette.ink.lighter,
  textFadedMax: palette.ink.lightest,
  primaryBackground: palette.primary.lightest,
  successBackground: 'rgba(216,243,220, 0.6)', // success.lightest
  primary: palette.primary.light,
  primaryLine: palette.primary.base,
  disabled: palette.light.base,
  link: palette.info.darkest,
  error: palette.error.darkest,
  icon: palette.ink.darkest,
  invertedIcon: palette.light.light,
  errorIcon: palette.error.base,
  errorLine: palette.error.base,
  inputBackground: palette.light.lightest,
  chipBackground: palette.primary.base,
  spotifyIcon: palette.spotify.primary,
  errorBackground: palette.error.lightest,
};
